server:
  port: 9003

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.132:8848
  application:
    name: nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'