#启动端口
server:
  port: 9527
#项目名称
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: work-routh   #路由的ID,没有固定的但要求唯一
#          uri: http://localhost:8001  #匹配提供服务的地址
          uri: lb:http://PROVIDER-WORK  #匹配提供服务的地址
          predicates:
            - Path=/work/get/** #路径匹配的进行路由

        - id: work-routh2
#          uri: http://localhost:8001
          uri: lb:http://PROVIDER-WORK  #匹配提供服务的地址
          predicates:
            - Path=/work/lb/**
      discovery:
        locator:
          enabled: true   #开启负载均衡 lb:http://PROVIDER-WORK

#eureka配置
eureka:
  instance:
    prefer-ip-address: true #使用服务的id地址注册
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      defaultZone: http://localhost:8761/eureka/

