server:
  port: 9083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.132:8848
  application:
    name: nacos-payment-consumer

server-url:
  nacos-user-service: http://nacos-payment-provider

